"""Added more columns to user

Revision ID: 05b05341aec4
Revises: e4747708cf7b
Create Date: 2023-04-04 20:22:06.061209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b05341aec4'
down_revision = 'e4747708cf7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('platoon', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('section', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_me')
        batch_op.drop_column('section')
        batch_op.drop_column('platoon')
        batch_op.drop_column('company')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
