"""empty message

Revision ID: 2eb32cba381a
Revises: f59ee816023d
Create Date: 2023-04-11 17:10:57.166282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb32cba381a'
down_revision = 'f59ee816023d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nominal_submitted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.drop_column('nominal_submitted')

    # ### end Alembic commands ###
