"""Added capacity to sport

Revision ID: 610cd961e781
Revises: 12896e22bf45
Create Date: 2023-04-05 11:38:06.578366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610cd961e781'
down_revision = '12896e22bf45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
