"""Added img src to Sport

Revision ID: c42973fec888
Revises: 610cd961e781
Create Date: 2023-04-05 11:45:04.665001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42973fec888'
down_revision = '610cd961e781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_src', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.drop_column('img_src')

    # ### end Alembic commands ###
