"""empty message

Revision ID: cd5f3a478559
Revises: fbb965d5d73a
Create Date: 2023-04-11 15:23:31.048570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5f3a478559'
down_revision = 'fbb965d5d73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nominal_submitted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.drop_column('nominal_submitted')

    # ### end Alembic commands ###
