"""empty message

Revision ID: f59ee816023d
Revises: cd5f3a478559
Create Date: 2023-04-11 15:37:33.248477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59ee816023d'
down_revision = 'cd5f3a478559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.drop_column('nominal_submitted')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nominal_submitted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nominal_submitted')

    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nominal_submitted', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
